import {
  mdiAccountCircleOutline,
  mdiAccountCogOutline,
  mdiAccountPlusOutline,
  mdiArrowLeft,
  mdiArrowUp,
  mdiAutoFix,
  mdiCameraOutline,
  mdiChartBoxOutline,
  mdiCheckboxBlankOutline,
  mdiCheckboxMarkedOutline,
  mdiCheck,
  mdiChevronDown,
  mdiChevronLeft,
  mdiChevronRight,
  mdiChevronUp,
  mdiClose,
  mdiCloseBoxMultipleOutline,
  mdiCloudDownloadOutline,
  mdiCogOutline,
  mdiCodeTags,
  mdiConnection,
  mdiCreationOutline,
  mdiCubeOutline,
  mdiDeleteOutline,
  mdiDownloadOutline,
  mdiFolderOutline,
  mdiFolderPlusOutline,
  mdiImageOutline,
  mdiMagnify,
  mdiMenu,
  mdiMessageTextOutline,
  mdiMinus,
  mdiPaletteOutline,
  mdiPaperclip,
  mdiPencilOutline,
  mdiPlus,
  mdiRefresh,
  mdiRobotOutline,
  mdiSend,
  mdiServer,
  mdiSourceBranch,
  mdiStop,
  mdiSwordCross,
  mdiTrophyOutline,
  mdiThemeLightDark,
  mdiTuneVariant,
  mdiUploadOutline,
  mdiUnfoldMoreHorizontal,
  mdiWindowMaximize,
  mdiWeatherNight,
  mdiWhiteBalanceSunny,
  mdiWrench,
} from "@mdi/js";
import { h } from "vue";
import type { IconProps, IconSet } from "vuetify";
import { VSvgIcon } from "vuetify/components";

const map: Record<string, string> = {
  "mdi-account-circle-outline": mdiAccountCircleOutline,
  "mdi-account-cog-outline": mdiAccountCogOutline,
  "mdi-account-plus-outline": mdiAccountPlusOutline,
  "mdi-arrow-left": mdiArrowLeft,
  "mdi-arrow-up": mdiArrowUp,
  "mdi-auto-fix": mdiAutoFix,
  "mdi-camera-outline": mdiCameraOutline,
  "mdi-chart-box-outline": mdiChartBoxOutline,
  "mdi-checkbox-blank-outline": mdiCheckboxBlankOutline,
  "mdi-checkbox-marked-outline": mdiCheckboxMarkedOutline,
  "mdi-check": mdiCheck,
  "mdi-chevron-down": mdiChevronDown,
  "mdi-chevron-left": mdiChevronLeft,
  "mdi-chevron-right": mdiChevronRight,
  "mdi-chevron-up": mdiChevronUp,
  "mdi-close": mdiClose,
  "mdi-close-box-multiple-outline": mdiCloseBoxMultipleOutline,
  "mdi-cloud-download-outline": mdiCloudDownloadOutline,
  "mdi-cog-outline": mdiCogOutline,
  "mdi-code-tags": mdiCodeTags,
  "mdi-connection": mdiConnection,
  "mdi-creation-outline": mdiCreationOutline,
  "mdi-cube-outline": mdiCubeOutline,
  "mdi-delete-outline": mdiDeleteOutline,
  "mdi-download-outline": mdiDownloadOutline,
  "mdi-folder-outline": mdiFolderOutline,
  "mdi-folder-plus-outline": mdiFolderPlusOutline,
  "mdi-image-outline": mdiImageOutline,
  "mdi-magnify": mdiMagnify,
  "mdi-menu": mdiMenu,
  "mdi-message-text-outline": mdiMessageTextOutline,
  "mdi-minus": mdiMinus,
  "mdi-palette-outline": mdiPaletteOutline,
  "mdi-paperclip": mdiPaperclip,
  "mdi-pencil-outline": mdiPencilOutline,
  "mdi-plus": mdiPlus,
  "mdi-refresh": mdiRefresh,
  "mdi-robot-outline": mdiRobotOutline,
  "mdi-send": mdiSend,
  "mdi-server": mdiServer,
  "mdi-source-branch": mdiSourceBranch,
  "mdi-stop": mdiStop,
  "mdi-sword-cross": mdiSwordCross,
  "mdi-trophy-outline": mdiTrophyOutline,
  "mdi-theme-light-dark": mdiThemeLightDark,
  "mdi-tune-variant": mdiTuneVariant,
  "mdi-upload-outline": mdiUploadOutline,
  "mdi-unfold-more-horizontal": mdiUnfoldMoreHorizontal,
  "mdi-window-maximize": mdiWindowMaximize,
  "mdi-weather-night": mdiWeatherNight,
  "mdi-white-balance-sunny": mdiWhiteBalanceSunny,
  "mdi-wrench": mdiWrench,
};

export const aerinaIconSet: IconSet = {
  component: (props: IconProps) => {
    const key = String(props.icon ?? "");
    const path = map[key] ?? key;
    return h(VSvgIcon, { ...props, icon: path });
  },
};
